#!/usr/bin/env perl
use 5.024;
use warnings;
use Path::Tiny 'path';
use lib path(__FILE__)->parent->parent->child('lib')->stringify;
use Mojolicious::Commands;
 
# Start command line interface for application
Mojolicious::Commands->start_app('Game::Torneo::API');
